-- LIVRARIA

INSERT INTO LIVRARIA (ID_LIVRARIA, NOME_LIVRARIA) VALUES (1,'HAGNOS LIVRARIA');

INSERT INTO LIVRARIA (ID_LIVRARIA, NOME_LIVRARIA) VALUES (2,'SARAIVA');

INSERT INTO LIVRARIA (ID_LIVRARIA, NOME_LIVRARIA) VALUES (3,'ESTANTE VIRTUAL');

INSERT INTO LIVRARIA (ID_LIVRARIA, NOME_LIVRARIA) VALUES (4,'BAURU SHOPPING');

INSERT INTO LIVRARIA (ID_LIVRARIA, NOME_LIVRARIA) VALUES (5,'LIVRARIA PRINCIPS');

INSERT INTO LIVRARIA (ID_LIVRARIA, NOME_LIVRARIA) VALUES (6,'HAGNOS LIVRARIA');

-- LOCALIDADE

INSERT INTO LOCALIDADE (ID_LOCAL, CIDADE, ESTADO, PAIS) 
    VALUES (1,'BAURU', 'SP', 'BRA');

INSERT INTO LOCALIDADE (ID_LOCAL, CIDADE, ESTADO, PAIS) 
    VALUES (2,'MARILIA', 'SP', 'BRA');

INSERT INTO LOCALIDADE (ID_LOCAL, CIDADE, ESTADO, PAIS) 
    VALUES (3,'TRÊS LAGOAS', 'MS', 'BRA');

INSERT INTO LOCALIDADE (ID_LOCAL, CIDADE, ESTADO, PAIS) 
    VALUES (6,'NOVA JERSEY', 'NW', 'EUA');

INSERT INTO LOCALIDADE (ID_LOCAL, CIDADE, ESTADO, PAIS) 
    VALUES (5,'NOVA YORK', 'NW', 'EUA');

-- FAIXA_IDADE

INSERT INTO FAIXA_IDADE (ID_FAIXA, DESCRICAO) VALUES (1,'APARTIR DE 10 ANOS');

INSERT INTO FAIXA_IDADE (ID_FAIXA, DESCRICAO) VALUES (2,'APARTIR DE 12 ANOS');

INSERT INTO FAIXA_IDADE (ID_FAIXA, DESCRICAO) VALUES (3,'APARTIR DE 14 ANOS');

INSERT INTO FAIXA_IDADE (ID_FAIXA, DESCRICAO) VALUES (4,'APARTIR DE 16 ANOS');

INSERT INTO FAIXA_IDADE (ID_FAIXA, DESCRICAO) VALUES (5,'APARTIR DE 18 ANOS');

-- TEMPO

INSERT INTO TEMPO (ID_TEMPO, MES, ANO) VALUES (1, 01, 2019);

INSERT INTO TEMPO (ID_TEMPO, MES, ANO) VALUES (2, 03, 2022);

INSERT INTO TEMPO (ID_TEMPO, MES, ANO) VALUES (3, 04, 2022);

INSERT INTO TEMPO (ID_TEMPO, MES, ANO) VALUES (4, 02, 2023);

INSERT INTO TEMPO (ID_TEMPO, MES, ANO) VALUES (5, 08, 2015);

INSERT INTO TEMPO (ID_TEMPO, MES, ANO) VALUES (6, 12, 2012);

-- AUTOR

INSERT INTO AUTOR (ID_AUTOR, NOME_AUTOR) VALUES (1, 'LEANDRO');

INSERT INTO AUTOR (ID_AUTOR, NOME_AUTOR) VALUES (2, 'RAFAEL');

INSERT INTO AUTOR (ID_AUTOR, NOME_AUTOR) VALUES (3, 'LUCAS');

INSERT INTO AUTOR (ID_AUTOR, NOME_AUTOR) VALUES (4, 'THATIANE');

INSERT INTO AUTOR (ID_AUTOR, NOME_AUTOR) VALUES (5, 'MARCELA');

INSERT INTO AUTOR (ID_AUTOR, NOME_AUTOR) VALUES (6, 'WAGNER');

-- EDITORA

INSERT INTO EDITORA (ID_EDITORA, NOME_EDITORA) VALUES (1, 'PRINCIPS');

INSERT INTO EDITORA (ID_EDITORA, NOME_EDITORA) VALUES (2, 'ROCCO');

INSERT INTO EDITORA (ID_EDITORA, NOME_EDITORA) VALUES (3, 'HAGNOS');

-- ASSUNTO

INSERT INTO ASSUNTO (ID_ASSUNTO, NOME_ASSUNTO) VALUES (1, 'ROMANCE');

INSERT INTO ASSUNTO (ID_ASSUNTO, NOME_ASSUNTO) VALUES (2, 'ALEGORIA');

INSERT INTO ASSUNTO (ID_ASSUNTO, NOME_ASSUNTO) VALUES (3, 'TEOLOGIA');

-- VENDA

INSERT INTO VENDA (
    ID_LIVRARIA, 
    ID_LOCAL,
    ID_TEMPO,
    ID_AUTOR,
    ID_EDITORA,
    ID_ASSUNTO,
    ID_FAIXA,
    GENERO,
    QUANTIDADE,
    VALOR
  ) VALUES (
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    'F',
    7,
    10.76
    );